print('Enter your name')
name=input()
print('Enter your age')
age=int(input())
print('Enter your birth year')
year=int(input())
print('You will become 100 years old in the following years-')
print(100-(age))
